<?php echo $this->headLink()->appendStylesheet($this->baseUrl('views/css/site/index/index.css')); ?> 
<div id="pages">
    <div id="site-index-index">
        <div class="sobre-sistema">
            texto
        </div>
        <div class="box-links">
            link 1
        </div>
        <div class="box-links">
            link 2
        </div>
        <div class="box-links">
            link 3
        </div>
    </div>
</div>
