<?php echo $this->headLink()->appendStylesheet($this->baseUrl('views/css/site/index/index.css')); ?> 
<div id="pages">
    <div id="site-index-index">
        <div id='box-1'>
            <div class="sobre-sistema">
                <p><h3>Sobre o Sistema</h3></p>
                <p>
                    <span class="paragrafo">
                        O NewFinances é um sistema de controle financeiro no qual você
                    </span>
                    <span>
                    poderá otimizar suas contas e gerenciar suas finanças de maneira
                    fácil e objetiva, controlando assim com total segurança suas 
                    receitas e despesas diárias.
                    </span>
                </p>
                <p>
                    <span class="paragrafo">
                    Hoje em dia é fundamental a necessidade de termos cada vez mais 
                    </span>
                    <span>
                    uma saúde financeira estável, no qual poderemos assim fazer 
                    aqueles investimentos tão sonhados: Aquela viagem internacional 
                    ou comprar o carro novo.
                    </span>
                </p>
                <p>
                    <span class="paragrafo">
                    O sistema é totalmente voltado para as famílias brasileiras, 
                    </span>
                    <span>
                    por isso a necessidade de desenvolvermos algo simples e prático,
                    simples na forma de usar o sistema e prático no qual os 
                    resultados são facilmente visíveis.
                    </span>
                </p>
                <p>
                    <span class="paragrafo">
                    Não perca tempo e cadastre-se agora mesmo e desfrute de todas 
                    </span>
                    <span>
                    as vantagens de ser um(a) usuário(a) do NewFinances. 
                    </span>
                </p>
                <p>
                    <span class="paragrafo">
                        São três <a href="<?php echo $this->url(array(
                                'module' => 'site',
                                'controller' => 'planos',
                                'action' => 'index'
                            ), null, true); ?>">planos</a> para você escolher. 
                        Você poderá também 
                    </span>
                    <span>
                        <b>experimentar por <font size='4'>30 dias</font> o NewFinances</b> antes de aderir a 
                        algum plano.
                    </span>
                </p>
            </div>
            <!--
            <div class='sobre-sistema'>
                <h3>Vantagnes do NewFinances</h3>
                <p>
                    <span class="paragrafo">
                        O NewFinances Controle Financeiro possui um princípio 
                    </span>
                    <span> de AI (Inteligência Artificial), ou seja, ele analiza e te ajuda 
                        a tomar as melhores decisões, inclusive "dando palpites" nas
                        suas receitas, despesa e cartão de crédito.
                    </span>
                </p>
            </div>
            -->
        </div>
        <div id='box-2'>
            <div class='news'>
                <div id="fb-root"></div>
                <script>
                    (function(d, s, id) {
                        var js, fjs = d.getElementsByTagName(s)[0];
                        if (d.getElementById(id)) return;
                        js = d.createElement(s); js.id = id;
                        js.src = "//connect.facebook.net/pt_BR/all.js#xfbml=1";
                        fjs.parentNode.insertBefore(js, fjs);
                    }(document, 'script', 'facebook-jssdk'));
                </script>
                <div class="fb-like-box" 
                     data-href="http://www.facebook.com/sisnewfinances" 
                     data-colorscheme="light" 
                     data-show-faces="true" 
                     data-header="true" 
                     data-stream="fasle" 
                     data-show-border="true">                
                </div>
            </div>
            <div class="news">
                <a class="twitter-timeline" href="https://twitter.com/NewFinances" data-widget-id="423853342851223552">Tweets de @NewFinances</a>
                <script>
                    !function(d,s,id){
                        var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';
                        if(!d.getElementById(id)){
                            js=d.createElement(s);
                            js.id=id;js.src=p+"://platform.twitter.com/widgets.js";
                            fjs.parentNode.insertBefore(js,fjs);
                        }
                    }(document,"script","twitter-wjs");
                </script>
            </div>
        </div>
        <!--
        <div class="box-links">
            Porque usar o NewFinances
        </div>
        <div class="box-links">
            link 2
        </div>
        <div class="box-links">
            link 3
        </div>
        -->
    </div>
</div>