<body>
    <div style="float: left; width: 70%; margin: 10px 15%; border: 1px solid #696969; padding: 0 7px;">
        <div style="float: left; width: 100%; height: 250px;">
            <img style="padding: 15px; width: 250px;" src="http://newfinances.com.br/views/img/logo_newfinances.png" />
            <div style="float: left; width: 100%; padding: 7px;">
                <h2 style="text-align: center; margin: 10px 0;">PLANO EXPIRADO</h2 >
                <p>Olá <?php echo $this->nome_completo; ?></p>
                <p>Seu plano expirou</p>
                <p>Você agora está cadastrado no plano Básico</p>
                <p>
                    Aproveite as vantegens dos planos Trimestral, Semestral e 
                    Anual que estão com preços imperdíveis e continue tendo 
                    acesso a todas as funcionalidade e facilidades do NewFinances
                </p>
                <p>Obrigado.</p>
            </div>
        </div>
        <div style="position: relative; bottom: 0; left: 0;">
            <p style="text-align: center;">E-mail gerado automaticamente. Por favor não responda ao mesmo.</p>
            <p style="font-size: 12px; margin-top: 13px;">Atenciosamente,</p>
            <p style="font-weight: bold; font-size: 12px; margin-bottom: 7px;">Equipe NewFinances - contato@newfinances.com.br</p>        
        </div>
    </div>
</body>