<?php echo $this->headLink()->appendStylesheet($this->baseUrl('views/css/site/planos/index.css')); ?>
<div id="pages">
    <div id="site-planos-index">
        <h3 class="titulo-laranja">Nossos Planos</h3>
        <p>
            Faça seu cadastro e escolha o plano que melhor lhe atende. É rápido, simples e com total segurança.
            <a class="color-blue margim-left-10px" href="<?php echo $this->url(array(
                'module' => 'cliente',
                'controller' => 'usuarios',
                'action' => 'novo-usuario'
            )); ?>">Quero me cadastrar</a>
        </p>
        <div class="box-planos">
            <form method="post">
                <div class="box-plano-trimestral">
                    <div class="titulo-plano bg_blue">Plano Trimestral</div>
                    <div class="valor-plano"><?php echo View_Helper_Currency::getCurrency($this->planoTrimestral->valor_plano); ?></div>
                    <div class="valor-mes-plano">apenas <?php echo View_Helper_Currency::getCurrency($this->planoTrimestral->valor_plano / 3); ?>/mês</div>
                    <input type="hidden" name="id_plano" id="id_plano" value="3" />
                    <input type="hidden" name="id_usuario" id="id_usuario" value="<?php echo $this->id_usuario; ?>" />
                    <!--<input type="submit" name="submit" class="submit" value="Escolher" />-->
                </div>
            </form>
            <form method="post">
                <div class="box-plano-anual">
                    <div class="titulo-plano bg_orange">Plano Anual</div>
                    <div class="valor-plano"><?php echo View_Helper_Currency::getCurrency($this->planoAnual->valor_plano); ?></div>
                    <div class="valor-mes-plano">apenas <?php echo View_Helper_Currency::getCurrency($this->planoAnual->valor_plano / 12); ?>/mês</div>
                    <div class="economia-plano">Economize <span class="valor-economia"><?php echo View_Helper_Planos::getEconomiaPlano($this->planoAnual); ?>%</span></div>
                    <input type="hidden" name="id_plano" id="id_plano" value="5" />
                    <input type="hidden" name="id_usuario" id="id_usuario" value="<?php echo $this->id_usuario; ?>" />
                    <!--<input type="submit" name="submit" class="submit" value="Escolher" />-->
                </div>
            </form>
            <form method="post">
                <div class="box-plano-semestral">
                    <div class="titulo-plano bg_green">Plano Semestral</div>
                    <div class="valor-plano"><?php echo View_Helper_Currency::getCurrency($this->planoSemestral->valor_plano); ?></div>
                    <div class="valor-mes-plano">apenas <?php echo View_Helper_Currency::getCurrency($this->planoSemestral->valor_plano / 6); ?>/mês</div>                
                    <div class="economia-plano">Economize <span class="valor-economia"><?php echo View_Helper_Planos::getEconomiaPlano($this->planoSemestral); ?>%</span></div>
                    <input type="hidden" name="id_plano" id="id_plano" value="4" />
                    <input type="hidden" name="id_usuario" id="id_usuario" value="<?php echo $this->id_usuario; ?>" />
                    <!--<input type="submit" name="submit" class="submit" value="Escolher" />-->
                </div>            
            </form>    
        </div>    
        <div id="experimente">
            Você pode experimentar o sistema pelo período de <?php echo $this->plano_experiencia; ?> dias
        </div>
        <div id="box-info">
            <p>
                Todos os planos dão direito de acesso à todas as funcionalidades
                do sistema.
                O pagamento é realizado através do parceiro 
                <img style="margin-top: 10px;" src="<?php echo $this->baseUrl('views/img/pagseguro.png'); ?>" width="80"/>
                com total segurança e agilidade.
            </p>
        </div>
    </div>
</div>