<?php echo $this->headLink()->appendStylesheet($this->baseUrl('views/css/site/planos/index.css')); ?>
<div id="pages">
    <div id="site-planos-index">
        <h3 class="titulo-laranja">Nossos Planos</h3>
        <div class="box-planos">
            <div class="box-plano-trimestral">
                <div class="titulo-plano bg_blue">Plano Trimestral</div>
                <div class="valor-plano">R$19,90</div>
                <div class="valor-mes-plano">apenas R$6,63/mês</div>
            </div>
            <div class="box-plano-anual">
                <div class="titulo-plano bg_orange">Plano Anual</div>
                <div class="valor-plano">R$39,90</div>
                <div class="valor-mes-plano">apenas R$3,33/mês</div>
                <div class="economia-plano">Economize <span class="valor-economia">50%</span></div>
            </div>
            <div class="box-plano-semestral">
                <div class="titulo-plano bg_green">Plano Semestral</div>
                <div class="valor-plano">R$27,90</div>
                <div class="valor-mes-plano">apenas R$4,65/mês</div>                
                <div class="economia-plano">Economize <span class="valor-economia">30%</span></div>
            </div>            
        </div>    
        <div id="experimente">
            Você pode experimentar o sistema pelo período de 30 dias
        </div>
        <div id="box-info">
            <p>
                Todos os planos dão direito de acesso à todas as funcionalidades
                do sistema.
                O pagamento é realizado através do parceiro 
                <img style="margin-top: 10px;" src="<?php echo $this->baseUrl('views/img/pagseguro.png'); ?>" width="80"/>
                com total segurança e agilidade.
            </p>
        </div>
    </div>
</div>