<?php echo $this->headLink()->appendStylesheet($this->baseUrl('views/css/relatorios/index.css')); ?>
<div id="pages">
    <div id="relatorios-categorias">
        <h2 class="titulo-laranja">Relatório Categorias</h2>
        <div class="lista-relatorio-anual">
            <table>
                <tr>
                    <th>Categoria</th>
                    <th>Meta</th>
                    <th>Gasto</th>
                    <th>Saldo</th>
                </tr>
                <?php foreach ($this->metasCategorias as $meta) : ?>
                <tr>
                    <td><?php echo $meta->descricao_categoria; ?></td>
                    <td><?php echo $meta->valor_meta; ?></td>
                    <td><?php echo $meta->gasto; ?></td>
                    <td><?php echo $meta->saldo; ?></td>
                </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>
</div>