<?php echo $this->headScript()->appendFile($this->baseUrl('views/js/index/index.js')); ?>
<div id="pages">
    <div id="index-index">
        <div class="box_1">
            <!-- top categorias -->
            <div class="fundo-visao-geral">
                <label>Top Categorias</label>
            </div>
            <table>
                <?php if ($this->gastosCategorias->count() > 0) : ?>
                    <tr>
                        <th>Categoria</th>
                        <th>Valor</th>
                        <th>Porcentagem</th>
                        <th>Ações</th>
                    </tr>                
                    <?php foreach ($this->gastosCategorias as $categoria) : ?>
                        <tr>
                            <td class="align_left">
                                <span><?php echo $categoria->descricao_categoria; ?></span>
                            </td>                    
                            <td class="align_right">
                                <span><?php echo View_Helper_Currency::getCurrency($categoria->total); ?></span>
                            </td>                    
                            <td class="align_center">
                                <span><?php echo View_Helper_Categorias::getPorcentagemGastCategoriaMesAtual($categoria->total); ?></span>
                            </td>
                            <td class="align_center">
                                <a href="">
                                    <img src="<?php echo $this->baseUrl('views/img/icon_list.png'); ?>" title="Ver Gastos" width="15"/>
                                </a>
                            </td>
                        </tr>                    
                    <?php endforeach; ?>
                <?php else : ?>
                    <tr class="align_center">
                        <td>Você ainda não tem nenhuma despesa lançada.</td>
                    </tr>
                <?php endif; ?>
            </table>
            <!-- pendencias -->
            <div class="fundo-visao-geral">
                <label>Pendências (<?php echo $this->pendencias->count(); ?>)</label>
            </div>
            <table>
                <?php if ($this->pendencias->count() > 0) : ?>                                        
                <tr>
                    <th>Data</th>
                    <th>Descrição</th>
                    <th>Valor</th>
                    <th colspan="3">Ações</th>
                </tr>
                    <?php foreach ($this->pendencias as $pendencia) : ?>
                    <tr class="align_center">
                        <td><?php echo View_Helper_Date::getDataView($pendencia->data_movimentacao); ?></td>
                        <td class="align_left"><?php echo $pendencia->descricao_movimentacao; ?></td>
                        <td class="align_right"><?php echo View_Helper_Currency::getCurrency($pendencia->valor_movimentacao); ?></td>
                        <td>
                            <a href="">
                                <img src="<?php echo $this->baseUrl('views/img/ok_gray.png'); ?>" title="Realizado" width="15"/>
                            </a>
                        </td>
                        <td>
                            <a href="">
                                <img src="<?php echo $this->baseUrl('views/img/icon_edit.png'); ?>" title="Editar" width="15"/>
                            </a>
                        </td>
                        <td>
                            <a href="">
                                <img src="<?php echo $this->baseUrl('views/img/icon_delete.png'); ?>" title="Excluir" width="15"/>
                            </a>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                <?php else : ?>
                <tr>
                    <td class="align_center">Nenhuma pendência</td>
                </tr>
                <?php endif; ?>
            </table>
        </div>    
        <div class="box_2">
            <!-- orcamentos -->
            <div class="fundo-visao-geral">
                <label>Orçamentos</label>
            </div>
            <table>
                <?php if ($this->metas->count() > 0) : ?>
                <tr>
                    <th>Categoria</th>
                    <th>Meta</th>
                    <th>Total Gasto</th>
                    <th>Porcentagem</th>
                    <th>Projeção</th>
                    <th colspan="2">Ações</th>
                </tr>                
                <?php foreach ($this->metas as $meta) : ?>
                <tr class="align_center">
                    <td class="align_left">
                        <span><?php echo $meta->descricao_categoria; ?></span>
                    </td>                    
                    <td>
                        <span><?php echo View_Helper_Currency::getCurrency($meta->valor_meta); ?></span>
                    </td>                    
                    <td>
                        <span><?php echo View_Helper_Currency::getCurrency($meta->total); ?></span>
                    </td>
                    <td>
                        <span><?php echo number_format($meta->porcentagem, 2, ',', ''); ?>%</span>
                    </td>
                    <td>
                        <span><?php echo View_Helper_Meta::getProjecaoMeta($meta->porcentagem); ?>%</span>
                    </td>
                    <td>
                        <a href="">
                            <img src="<?php echo $this->baseUrl('views/img/icon_list.png'); ?>" title="Ver Gastos" width="15"/>
                        </a>
                    </td>
                    <td>
                        <a href="">
                            <img src="<?php echo $this->baseUrl('views/img/icon_edit.png'); ?>" title="Ver Gastos" width="15"/>
                        </a>
                    </td>
                </tr>                    
                <?php endforeach; ?>
                <!--
                <tr>
                    <th>Total: </th>
                    <td><?php echo View_Helper_Currency::getCurrency($this->total_meta); ?></td>
                    <td><?php echo View_Helper_Currency::getCurrency($this->total_gastos); ?></td>
                    <td><?php echo View_Helper_Meta::getPorcentagemTotalGastos($this->total_meta, $this->total_gastos); ?></td>
                    <td><?php echo View_Helper_Meta::getProjecaoMeta(View_Helper_Meta::getPorcentagemTotalGastos($this->total_meta, $this->total_gastos)); ?>%</td>
                    <td>&nbsp;</td>
                </tr>
                -->
                <?php else : ?>
                <tr>
                    <td class="align_center">Você ainda não gastou sobre nunhuma meta cadastrada.</td>
                </tr>
                <?php endif; ?>
            </table>
            <!-- receitas -->
            <div class="fundo-visao-geral">
                <label>Receitas (<?php echo $this->receitas->count(); ?>)</label>
            </div>
            <table>
                <?php if ($this->receitas->count() > 0) : ?>
                <tr>
                    <th>Data</th>
                    <th>Descrição</th>
                    <th>Valor</th>
                </tr>
                <?php foreach ($this->receitas as $receita) : ?>
                <tr class="align_center">
                    <td><?php echo View_Helper_Date::getDataView($receita->data_movimentacao); ?></td>
                    <td class="align_left"><?php echo $receita->descricao_movimentacao; ?></td>
                    <td><?php echo View_Helper_Currency::getCurrency($receita->valor_movimentacao); ?></td>
                </tr>
                <?php endforeach; ?>
                <?php else : ?>
                <tr>
                    <td class="align_center">Nenhuma receita futura</td>
                </tr>
                <?php endif; ?>
            </table>
            <!-- despesas -->
            <div class="fundo-visao-geral">
                <label>Despesas (<?php echo $this->despesas->count(); ?>)</label>
            </div>
            <table>
                <?php if ($this->despesas->count() > 0) : ?>
                <tr>
                    <th>Data</th>
                    <th>Descrição</th>
                    <th>Valor</th>
                </tr>
                    <?php foreach ($this->despesas as $despesa) : ?>
                    <tr class="align_center">
                        <td><?php echo View_Helper_Date::getDataView($despesa->data_movimentacao); ?></td>
                        <td class="align_left"><?php echo $despesa->descricao_movimentacao; ?></td>
                        <td><?php echo View_Helper_Currency::getCurrency($despesa->valor_movimentacao); ?></td>
                    </tr>
                    <?php endforeach; ?>
                <?php else : ?>
                <tr>
                    <td class="align_center">Nenhuma despesa futura</td>
                </tr>
                <?php endif; ?>
            </table> 
        </div>
    </div>
</div>