<?php echo $this->headScript()->appendFile($this->baseUrl('views/js/index/index.js')); ?>
<?php echo $this->headLink()->appendStylesheet($this->baseUrl('views/css/movimentacoes/index.css')); ?>
<?php echo $this->headScript()->appendFile($this->baseUrl('views/js/movimentacoes/index.js')); ?>
<div id="pages">
    <div id="index-index">
        <h3 class=" margim-top-10px margim-left-10px titulo-laranja">Lançamentos do Dia</h3>
        <div class="box">            
            <?php if ($this->movimentacoes->count() > 0) : ?>
                <div id="subtitulo-lista">
                    <div class="subtitulo-tipo">TIPO</div>
                    <div class="subtitulo-descricao">DESCRIÇÃO</div>
                    <div class="subtitulo-categoria">CATEGORIA</div>
                    <div class="subtitulo-valor">VALOR</div>
                    <div class="subtitulo-status">STATUS</div>
                    <div class="subtitulo-acoes">AÇÕES</div>
                </div>
                <?php foreach ($this->movimentacoes as $movimentacao) : ?>
                <div id='dados-movimentacao' class="<?php echo (View_Helper_Date::isPending($movimentacao)) ? 'pendente' : ''; ?>">  
                    <div class="tipo-movimentacao">
                        <?php echo View_Helper_TipoMovimentacao::getTipoMovimentacaoImage($movimentacao->id_tipo_movimentacao); ?>
                    </div>
                    <div class="descricao-movimentacao">
                        <?php echo (View_Helper_Date::isPending($movimentacao)) ? '' : ''; ?>
                        <?php echo $movimentacao->descricao_movimentacao; ?>
                        <br />
                        <span class="descricao-mini">
                            <?php if ($movimentacao->id_tipo_movimentacao == 4) : ?>                            
                            De <?php echo $movimentacao->descricao_conta; ?>
                            Para <?php echo $movimentacao->descricao_conta_destino; ?>
                            <?php elseif ($movimentacao->id_tipo_movimentacao == 1 || $movimentacao->id_tipo_movimentacao == 2) : ?>
                            Conta: <?php echo $movimentacao->descricao_conta; ?>
                            <?php elseif ($movimentacao->id_tipo_movimentacao == 3) : ?>
                            Cartão: <?php echo $movimentacao->descricao_cartao; ?>
                            <?php endif; ?>                                
                        </span>                            
                    </div>
                    <div class="categoria-movimentacao">
                        <?php echo $movimentacao->descricao_categoria; ?>
                    </div>                    
                    <div class="valor-movimentacao">
                        <?php echo View_Helper_Currency::getCurrency($movimentacao->valor_movimentacao); ?>
                    </div>                    
                    <div class="status-movimentacao">
                        <?php if (!in_array($movimentacao->id_tipo_movimentacao, array(0,5,3,6))) : ?>
                            <?php if ((bool)$movimentacao->realizado) : ?>
                            <a href="javascript:status(<?php echo $movimentacao->id_movimentacao; ?>, 1);">
                                <img src="<?php echo $this->baseUrl('views/img/ok_green.png'); ?>" title="Realizado" />                                    
                            </a>                            
                            <?php else : ?>
                            <a href="javascript:status(<?php echo $movimentacao->id_movimentacao; ?>, 0);">
                                <img src="<?php echo $this->baseUrl('views/img/ok_gray.png'); ?>" title="Previsto" />                                    
                            </a>
                            <?php endif; ?>                            
                        <?php elseif ($movimentacao->id_tipo_movimentacao == 6) : ?>
                        <a href="<?php echo $this->url(array(
                            'module' => 'cliente',
                            'controller' => 'cartoes',
                            'action' => 'ver-fatura',
                            'id_cartao' => $movimentacao->id_cartao,
                            'vencimento' => $movimentacao->data_movimentacao
                        )); ?>">
                            <img src="<?php echo $this->baseUrl('views/img/icon_list.png'); ?>" title="Ver Fatura" />
                        </a>
                        <a href="<?php echo $this->url(array(
                            'module' => 'cliente',
                            'controller' => 'cartoes',
                            'action' => 'pagar-fatura',
                            'id_cartao' => $movimentacao->id_cartao,
                            'vencimento' => $movimentacao->data_movimentacao
                        )); ?>">
                            <img src="<?php echo $this->baseUrl('views/img/icon_pay.png'); ?>" title="Pagar Fatura" />
                        </a>
                        <?php endif; ?>
                    </div>                                  
                    <div class="acoes-movimentacao">                                                        
                        <?php if (!in_array($movimentacao->id_tipo_movimentacao, array(0,5))) : ?>
                            <?php if ($movimentacao->id_tipo_movimentacao != 4) : ?>
                            <a href="<?php echo $this->url(array(
                                'module' => 'cliente',
                                'controller' => 'movimentacoes',
                                'action' => 'editar-movimentacao',
                                'id_movimentacao' => $movimentacao->id_movimentacao                                                                    
                            )); ?>">
                                <img src="<?php echo $this->baseUrl('views/img/icon_edit.png'); ?>" title="Editar" />
                            </a>
                            <?php endif; ?>
                        <a href="<?php echo $this->url(array(
                            'module' => 'cliente',
                                'controller' => 'movimentacoes',
                            'action' => 'excluir-movimentacao',
                            'id_movimentacao' => $movimentacao->id_movimentacao 
                        )); ?>">
                            <img src="<?php echo $this->baseUrl('views/img/icon_delete.png'); ?>" title="Excluir" />
                        </a>
                        <?php elseif ($movimentacao->fatura) : ?>
                        <a href="<?php echo $this->url(array(
                                'controller' => 'cartoes',
                                'action' => 'ver-fatura',
                                'id_cartao' => $movimentacao->id_cartao,
                                'vencimento' => $movimentacao->data_movimentacao
                            )); ?>">
                            <img src="<?php echo $this->baseUrl('views/img/icon_list.png'); ?>" title="Ver Fatura" />
                        </a>
                        <a href="<?php echo $this->url(array(
                                'controller' => 'cartoes',
                                'action' => 'pagar-fatura',
                                'id_cartao' => $movimentacao->id_cartao,
                                'vencimento' => $movimentacao->data_movimentacao
                            )); ?>">
                            <img src="<?php echo $this->baseUrl('views/img/icon_pay.png'); ?>" title="Pagar" />
                        </a>
                        <?php endif; ?>
                    </div>
                </div>
                <?php endforeach; ?>
            <?php else : ?>
            <center>Nenhum lançamento para hoje</center>
            <?php endif; ?>
        </div>
        <!-- cartoes de credito -->
        <h3 class="titulo-laranja margim-left-10px">Cartões de Crédito</h3>
        <div>
            <?php if($this->faturasCartoes->count() > 0) : ?>
            <table>
                <tr>
                    <th>Cartão</th>
                    <th>Bandeira</th>
                    <th>Vencimento</th>
                    <th>Total Fatura</th>
                    <th>Ações</th>
                </tr>
                <?php foreach ($this->faturasCartoes as $fatura) : ?>
                <tr>
                    <td><?php echo $fatura->descricao_cartao; ?></td>
                    <td class="align_center"><?php echo ucfirst($fatura->bandeira_cartao); ?></td>
                    <td class="align_center"><?php echo View_Helper_Date::getDataView($fatura->vencimento_fatura); ?></td>
                    <td class="align_right"><?php echo View_Helper_Currency::getCurrency($fatura->valor_fatura); ?></td>
                    <td class="align_center">
                        <a href="<?php echo $this->url(array(
                            'module' => 'cliente',
                            'controller' => 'cartoes',
                            'action' => 'ver-fatura',
                            'id_cartao' => $fatura->id_cartao,
                            'vencimento' => $fatura->vencimento_fatura
                        )); ?>">
                            <img src="<?php echo $this->baseUrl('views/img/icon_list.png'); ?>" title="Ver Fatura" width="15"/>
                        </a>
                    </td>
                </tr>
                <?php endforeach; ?>
            </table>
            <?php else : ?>
            <center>Nenhum cartão cadastrado ou fatura para este mês</center>
            <?php endif; ?>
        </div>
        <div class="box_1">
            <!-- top categorias -->
            <h3 class="titulo-laranja margim-left-10px">Top Categorias</h3>
            <table>
                <?php if ($this->gastosCategorias->count() > 0) : ?>
                    <tr>
                        <th>Nº</th>
                        <th>Categoria</th>
                        <th>Valor</th>
                        <th>Porcentagem</th>
                        <th>Ações</th>
                    </tr>        
                    <?php $count = 1; ?>
                    <?php foreach ($this->gastosCategorias as $categoria) : ?>
                        <tr>
                            <td class="align_center"><?php echo $count; ?>º</td>
                            <td class="align_left"><?php echo $categoria->descricao_categoria; ?></td>                    
                            <td class="align_right">
                                <?php echo View_Helper_Currency::getCurrency($categoria->total); ?><br />
                                <span class="descricao-mini">Previsto: <?php echo View_Helper_Categorias::getValorPrevistoCategoria($categoria->id_categoria); ?></span>
                            </td>                    
                            <td class="align_center"><?php echo View_Helper_Categorias::getPorcentagemGastCategoriaMesAtual($categoria->total); ?></td>                            
                            <td class="align_center">
                                <a href="<?php echo $this->url(array(
                                    'module' => 'cliente',
                                    'controller' => 'categorias',
                                    'action' => 'listar-gastos',
                                    'id_categoria' => $categoria->id_categoria
                                )); ?>">
                                    <img src="<?php echo $this->baseUrl('views/img/icon_list.png'); ?>" title="Ver Gastos" width="15"/>
                                </a>
                            </td>
                        </tr>                    
                        <?php $count++; ?>
                    <?php endforeach; ?>                    
                <?php else : ?>
                    <tr class="align_center">
                        <td>Você ainda não tem nenhuma despesa lançada.</td>
                    </tr>
                <?php endif; ?>
            </table>
            <!-- pendencias -->
            <h3 class="titulo-laranja margim-left-10px">Pendências (<?php echo $this->pendencias->count(); ?>)</h3>            
            <table>
                <?php if ($this->pendencias->count() > 0) : ?>                                        
                <tr>
                    <th>Data</th>
                    <th>Descrição</th>
                    <th>Valor</th>
                    <th colspan="3">Ações</th>
                </tr>
                    <?php foreach ($this->pendencias as $pendencia) : ?>
                    <tr class="align_center">
                        <td><?php echo View_Helper_Date::getDataView($pendencia->data_movimentacao); ?></td>
                        <td class="align_left"><?php echo $pendencia->descricao_movimentacao; ?></td>
                        <td class="align_right"><?php echo View_Helper_Currency::getCurrency($pendencia->valor_movimentacao); ?></td>
                        <td>
                            <a href="<?php echo $this->url(array(
                                'module' => 'cliente',
                                'controller' => 'movimentacoes',
                                'action' => 'status',
                                'id_movimentacao' => $pendencia->id_movimentacao,
                                'status' => $pendencia->realizado
                            )); ?>">
                                <img src="<?php echo $this->baseUrl('views/img/ok_gray.png'); ?>" title="Realizado" width="15"/>
                            </a>
                        </td>
                        <td>
                            <a href="<?php echo $this->url(array(
                                'module' => 'cliente',
                                'controller' => 'movimentacoes',
                                'action' => 'editar-movimentacao',
                                'id_movimentacao' => $pendencia->id_movimentacao
                            )); ?>">
                                <img src="<?php echo $this->baseUrl('views/img/icon_edit.png'); ?>" title="Editar" width="15"/>
                            </a>
                        </td>
                        <td>
                            <a href="<?php echo $this->url(array(
                                'module' => 'cliente',
                                'controller' => 'movimentacoes',
                                'action' => 'excluir-movimentacao',
                                'id_movimentacao' => $pendencia->id_movimentacao
                            )); ?>">
                                <img src="<?php echo $this->baseUrl('views/img/icon_delete.png'); ?>" title="Excluir" width="15"/>
                            </a>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                <?php else : ?>
                <tr>
                    <td class="align_center">Nenhuma pendência</td>
                </tr>
                <?php endif; ?>
            </table>
        </div>    
        <div class="box_2">
            <?php if (View_Helper_Application::hasAcl("cliente:metas")) : ?>            
            <!-- orcamentos -->
            <h3 class="titulo-laranja margim-left-10px">Orçamentos</h3>
            <table>
                <?php if ($this->metas->count() > 0) : ?>
                <tr>
                    <th>Categoria</th>
                    <th>Meta</th>
                    <th>Total Gasto</th>
                    <th>Porcentagem</th>
                    <th>Projeção</th>
                    <th>Sinal</th>
                    <th colspan="2">Ações</th>
                </tr>                
                <?php foreach ($this->metas as $meta) : ?>
                <tr class="align_center">                    
                    <td class="align_left"><?php echo $meta->descricao_categoria; ?></td>                    
                    <td><?php echo View_Helper_Currency::getCurrency($meta->valor_meta); ?></td>                    
                    <td><?php echo View_Helper_Currency::getCurrency($meta->total); ?></td>
                    <td><?php echo number_format($meta->porcentagem, 2, ',', ''); ?>%</td>
                    <td><?php echo View_Helper_Meta::getProjecaoMeta($meta->porcentagem); ?>%</td>
                    <td><?php echo View_Helper_Meta::getColorMeta($meta->porcentagem); ?></td>
                    <td>
                        <a href="<?php echo $this->url(array(
                            'module' => 'cliente',
                            'controller' => 'metas',
                            'action' => 'editar-meta',
                            'id_meta' => $meta->id_meta
                        )); ?>">
                            <img src="<?php echo $this->baseUrl('views/img/icon_edit.png'); ?>" title="Editar Orçamento" width="15"/>
                        </a>
                    </td>
                </tr>                    
                <?php endforeach; ?>
                <!--
                <tr>
                    <th>Total: </th>
                    <td><?php echo View_Helper_Currency::getCurrency($this->total_meta); ?></td>
                    <td><?php echo View_Helper_Currency::getCurrency($this->total_gastos); ?></td>
                    <td><?php echo View_Helper_Meta::getPorcentagemTotalGastos($this->total_meta, $this->total_gastos); ?></td>
                    <td><?php echo View_Helper_Meta::getProjecaoMeta(View_Helper_Meta::getPorcentagemTotalGastos($this->total_meta, $this->total_gastos)); ?>%</td>
                    <td>&nbsp;</td>
                </tr>
                -->
                <?php else : ?>
                <tr>
                    <td class="align_center">Você ainda não gastou sobre nunhuma meta cadastrada.</td>
                </tr>
                <?php endif; ?>
            </table>
            <?php endif; ?>
            <!-- receitas -->
            <h3 class="titulo-laranja margim-left-10px">Receitas (<?php echo $this->receitas->count(); ?>)</h3>            
            <table>
                <?php if ($this->receitas->count() > 0) : ?>
                <tr>
                    <th>Data</th>
                    <th>Descrição</th>
                    <th>Valor</th>
                </tr>
                <?php foreach ($this->receitas as $receita) : ?>
                <tr class="align_center">
                    <td><?php echo View_Helper_Date::getDataView($receita->data_movimentacao); ?></td>
                    <td class="align_left"><?php echo $receita->descricao_movimentacao; ?></td>
                    <td><?php echo View_Helper_Currency::getCurrency($receita->valor_movimentacao); ?></td>
                </tr>
                <?php endforeach; ?>
                <?php else : ?>
                <tr>
                    <td class="align_center">Nenhuma receita futura</td>
                </tr>
                <?php endif; ?>
            </table>
            <!-- despesas -->
            <h3 class="titulo-laranja margim-left-10px">Despesas (<?php echo $this->despesas->count(); ?>)</h3>
            <table>
                <?php if ($this->despesas->count() > 0) : ?>
                <tr>
                    <th>Data</th>
                    <th>Descrição</th>
                    <th>Valor</th>
                </tr>
                    <?php foreach ($this->despesas as $despesa) : ?>
                    <tr class="align_center">
                        <td><?php echo View_Helper_Date::getDataView($despesa->data_movimentacao); ?></td>
                        <td class="align_left"><?php echo $despesa->descricao_movimentacao; ?></td>
                        <td><?php echo View_Helper_Currency::getCurrency($despesa->valor_movimentacao); ?></td>
                    </tr>
                    <?php endforeach; ?>
                <?php else : ?>
                <tr>
                    <td class="align_center">Nenhuma despesa futura</td>
                </tr>
                <?php endif; ?>
            </table> 
        </div>
    </div>
</div>