<?php echo $this->headScript()->appendFile($this->baseUrl('views/js/cartoes/ver-fatura.js')); ?>
<div id='pages'>
    <div id='cartoes-ver-fatura'>
        <div class="listar-faturas">
            <div id="options-bar">
                <?php echo $this->formFaturas; ?>
            </div>
            <table class="tabless-green">
                <tr>
                    <td>Data</td>
                    <td>Descrição</td>
                    <td>Categoria</td>
                    <td>Valor</td>
                    <td colspan="2">Ações</td>
                </tr>
                <?php if ($this->lancamentosFatura->count() > 0) : ?>
                <?php foreach ($this->lancamentosFatura as $lancamento) : ?>
                <tr>
                    <td class="align_center"><?php echo View_Helper_Date::getDataView($lancamento->data_movimentacao); ?></td>
                    <td><?php echo $lancamento->descricao_movimentacao; ?></td>
                    <td><?php echo $lancamento->descricao_categoria; ?></td>
                    <td class="align_right"><?php echo View_Helper_Currency::getCurrency($lancamento->valor_movimentacao); ?></td>
                    <td class="align_center">
                        <a href="<?php echo $this->url(array(
                            'controller' => 'movimentacoes',
                            'action' => 'editar-movimentacao',
                            'id_movimentacao' => $lancamento->id_movimentacao
                        ), null, true); ?>">
                            <img class="img-actions" src="<?php echo $this->baseUrl('views/img/icon_edit.png'); ?>" title="Editar" />
                        </a>
                    </td>
                    <td class="align_center">
                        <a href="<?php echo $this->url(array(
                            'controller' => 'movimentacoes',
                            'action' => 'excluir-movimentacao',
                            'id_movimentacao' => $lancamento->id_movimentacao
                        ), null, true); ?>">
                            <img class="img-actions" src="<?php echo $this->baseUrl('views/img/icon_delete.png'); ?>" title="Excluir" />
                        </a>
                    </td>
                </tr>
                <?php endforeach; ?>
                <?php else : ?>
                <tr>
                    <td>Nenhuma movimentação</td>
                </tr>
                <?php endif; ?>
            </table>
        </div>
    </div>
</div>