<div class="info-pagseguro align_justify">
    <p>
        <h4 style="color: red">ATENÇÃO: </h4></p>
    </p>
    <p>
        Ao escolher seu plano você será redirecionado para o site do 
        <img src="<?php echo $this->baseUrl('views/img/pagseguro.png'); ?>" width="90"/>
        para realizar o pagamento do mesmo. Após finalizado o pagamento 
        você será redirecionado novamente para o nosso sistema.
    </p>
    <p>
        A avaliação do pagamento é automática, assim que o sistema receber
        a notificação do pagamento, seu plano será liberado e você irá
        receber uma notificação no e-mail cadastrado.
    </p>
</div>