<?php echo $this->headLink()->appendStylesheet($this->baseUrl('views/css/planos/alterar-plano.css')); ?>
<div id="pages">
    <div id="plano-usuario">
        <?php echo View_Helper_Messeges::getMessages($this->messages); ?>
        <div class="dados-usuario">
            <span>Olá <?php echo $this->dadosUsuario->nome_completo; ?></span>
        </div>
        <?php foreach ($this->formPlanosUsuario->id_plano->getMultiOptions() as $key => $form) : ?>
            <form method="<?php echo $this->formPlanosUsuario->getMethod(); ?>" id="<?php echo $this->formPlanosUsuario->getAttrib('id'); ?>">                
                <?php $class = View_Helper_Planos::getClassBannerPlano($key); ?>                
                <div id="<?php echo $class; ?>">
                    <input type="hidden" name="id_plano" id="id_plano" value="<?php echo $key; ?>" />
                    <?php echo $this->formPlanosUsuario->id_usuario; ?>
                    <div class="descricao-plano">
                        <?php echo $form; ?>
                    </div>  
                    <?php echo $this->formPlanosUsuario->cupom; ?>
                    <?php echo $this->formPlanosUsuario->submit; ?>
                    
                </div>
            </form>
        <?php endforeach; ?>
        <center>
            <?php if ($this->flagExperience) : ?>
            <!-- experimentar o plano por 30 dias -->
            <div class="plano-trial">
                <form method="<?php echo $this->formPlanosUsuario->getMethod(); ?>" id="<?php echo $this->formPlanosUsuario->getAttrib('id'); ?>">                
                    <input type="hidden" name="id_plano" id="id_plano" value="<?php echo $this->planoExperiencia->id_plano; ?>" />
                    <?php echo $this->formPlanosUsuario->id_usuario; ?>
                    <center>
                        <?php echo $this->formPlanosUsuario->submit->setLabel(
                            "Experimente por 30 dias"
                        ); ?>
                    </center>                    
                </form>
            </div>
            <?php endif; ?>
            <!-- escolher continuar no plano basico -->
            <div class="choise-basico">
                <a href="<?php echo $this->url(array(
                    'module' => 'cliente',
                    'controller' => 'index',
                    'action' => 'index'
                ), null, true); ?>" class="plano-basico">
                    <span>Continuar no plano atual</span>
                </a>
            </div>
        </center>
        <?php echo $this->partial('planos/info-pagamento.phtml'); ?>
    </div>
</div>