<?php echo $this->headLink()->appendStylesheet($this->baseUrl('views/css/planos/alterar-plano.css')); ?>
<?php echo $this->headLink()->appendStylesheet($this->baseUrl('views/css/site/planos/index.css')); ?>
<div id="pages">
    <div id="plano-usuario">
        <?php echo View_Helper_Messeges::getMessages($this->messages); ?>
        <div class="dados-usuario">
            <span>Olá <?php echo $this->dadosUsuario->nome_completo; ?></span>
        </div>        
        <div class="box-planos">
            <form method="post">
                <div class="box-plano-trimestral">
                    <div class="titulo-plano bg_blue">Plano Trimestral</div>
                    <div class="valor-plano"><?php echo View_Helper_Currency::getCurrency($this->planoTrimestral->valor_plano); ?></div>
                    <div class="valor-mes-plano">apenas <?php echo View_Helper_Currency::getCurrency($this->planoTrimestral->valor_plano / 3); ?>/mês</div>
                    <input type="hidden" name="id_plano" id="id_plano" value="3" />
                    <input type="hidden" name="id_usuario" id="id_usuario" value="<?php echo $this->id_usuario; ?>" />
                    <input type="submit" name="submit" class="submit" value="Escolher" />
                </div>
            </form>
            <form method="post">
                <div class="box-plano-anual">
                    <div class="titulo-plano bg_orange">Plano Anual</div>
                    <div class="valor-plano"><?php echo View_Helper_Currency::getCurrency($this->planoAnual->valor_plano); ?></div>
                    <div class="valor-mes-plano">apenas <?php echo View_Helper_Currency::getCurrency($this->planoAnual->valor_plano / 12); ?>/mês</div>
                    <div class="economia-plano">Economize <span class="valor-economia"><?php echo View_Helper_Planos::getEconomiaPlano($this->planoAnual); ?>%</span></div>
                    <input type="hidden" name="id_plano" id="id_plano" value="5" />
                    <input type="hidden" name="id_usuario" id="id_usuario" value="<?php echo $this->id_usuario; ?>" />
                    <input type="submit" name="submit" class="submit" value="Escolher" />
                </div>
            </form>
            <form method="post">
                <div class="box-plano-semestral">
                    <div class="titulo-plano bg_green">Plano Semestral</div>
                    <div class="valor-plano"><?php echo View_Helper_Currency::getCurrency($this->planoSemestral->valor_plano); ?></div>
                    <div class="valor-mes-plano">apenas <?php echo View_Helper_Currency::getCurrency($this->planoSemestral->valor_plano / 6); ?>/mês</div>                
                    <div class="economia-plano">Economize <span class="valor-economia"><?php echo View_Helper_Planos::getEconomiaPlano($this->planoSemestral); ?>%</span></div>
                    <input type="hidden" name="id_plano" id="id_plano" value="4" />
                    <input type="hidden" name="id_usuario" id="id_usuario" value="<?php echo $this->id_usuario; ?>" />
                    <input type="submit" name="submit" class="submit" value="Escolher" />
                </div>            
            </form>    
        </div>            
        <center>
            <?php if ($this->flagExperience) : ?>
            <!-- experimentar o plano por 30 dias -->
            <div class="plano-trial">
                <form method="<?php echo $this->formPlanosUsuario->getMethod(); ?>" id="<?php echo $this->formPlanosUsuario->getAttrib('id'); ?>">                
                    <input type="hidden" name="id_plano" id="id_plano" value="<?php echo $this->planoExperiencia->id_plano; ?>" />
                    <?php echo $this->formPlanosUsuario->id_usuario; ?>
                    <center>
                        <?php echo $this->formPlanosUsuario->submit->setLabel(
                            "Experimente por 30 dias"
                        ); ?>
                    </center>                    
                </form>
            </div>
            <?php endif; ?>
            <!-- escolher continuar no plano basico -->
            <div class="choise-basico">
                <a href="<?php echo $this->url(array(
                    'module' => 'cliente',
                    'controller' => 'index',
                    'action' => 'index'
                ), null, true); ?>" class="plano-basico">
                    <span>Continuar no plano atual</span>
                </a>
            </div>
        </center>        
    </div>
</div>