<div id="pages">
    <div id="usuarios-ativar">
        <p>
            <h2>Cadastro realizado com sucesso.</h2>
            <span>
                Seu cadastro foi realizado com sucesso, por favor acesse o link
                enviado para o e-mail cadastrado para ativar sua conta. 
            </span>
        </p>
        <p>Desde já a equipe NewFinances lhe da as boas vindas</p>
    </div>
</div>
