<?php echo $this->headScript()->appendFile($this->baseUrl('views/js/usuario/login.js')); ?>
<?php echo $this->headLink()->appendStylesheet($this->baseUrl('views/css/usuarios/login.css')); ?> 
<div id="usuarios-login">
    <div id="pages">
        <div class="site-area">
            <div class="menus">
                <ul>
                    <li>
                        <a href="">Sobre o sistema</a>
                    </li>
                    <li>
                        <a href="">Nossos planos</a>
                    </li>
                    <li>
                        <a href="">Política de Privacidade</a>
                    </li>
                    <li>
                        <a href="">Termo de compromisso</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="login-area">
            <form method="post">
                <table>
                    <tr>
                        <td colspan="2"><?php echo $this->formUsuariosLogin->email_usuario; ?></td>
                    </tr>
                    <tr>
                        <td colspan="2"><?php echo $this->formUsuariosLogin->senha_usuario; ?></td>
                    </tr>
                    <tr>
                        <td><?php echo $this->formUsuariosLogin->submit; ?></td>                        
                    </tr>
                </table>
                <center><a href="<?php echo $this->url(array(
                    'module' => 'cliente',
                    'controller' => 'usuarios',
                    'action' => 'recuperar-senha'
                )); ?>">Esqueci a senha</a></center>
            </form>            
            <div class="bar">
                <ul>
                    <li>
                        <a href="<?php echo $this->url(array(
                            'controller' => 'usuarios',
                            'action' => 'novo-usuario'
                        ), null, true); ?>">Cadastre-se</a><br />
                    </li>
                </ul>
            </div>
        </div>    
    </div>
</div>