<?php echo $this->headLink()->appendStylesheet($this->baseUrl('views/css/movimentacoes/excluir.css')); ?>
<div id="pages">
    <div id="excluir-movimentacao">
        <p class="message-excluir">
            <label>Tem certeza que deseja excluir essa movimentacao?</label>
        </p>
        <p class="lancamento">            
            <?php echo View_Helper_Date::getDataView($this->dadosMovimentacao->data_movimentacao); ?> | 
            <?php echo $this->dadosMovimentacao->descricao_movimentacao; ?> | 
            <?php echo View_Helper_Currency::getCurrency($this->dadosMovimentacao->valor_movimentacao); ?>
        </p>
        <form method="post">
            <p>
                <input type="submit" class="submit" name="btnResposta" value="Sim Apagar" />
                <input type="submit" class="submit" name="btnResposta" value="Cancelar" />
            </p>        
        </form>
    </div>
</div>