<div id="pages">
    <div id="gestor-chamados-index">
        <div class="lista-chamados">
            <table class="tabless-green">
                <tr>
                    <td>Data</td>
                    <td>Usuário</td>
                    <td>Tipo Chamado</td>
                    <td>Assunto</td>
                    <td>Status</td>                    
                    <td>Ações</td>                    
                </tr>
                <?php foreach ($this->chamados as $chamado) : ?>
                <tr>
                    <td><?php echo View_Helper_Date::getDateTimeView($chamado->data_abertura); ?></td>
                    <td><?php echo $chamado->nome_completo; ?></td>
                    <td><?php echo $chamado->descricao; ?></td>
                    <td><?php echo $chamado->assunto; ?></td>
                    <td><?php echo $chamado->status; ?></td>
                    <td>
                        <a href="<?php echo $this->url(array(
                            'module' => 'gestor',
                            'controller' => 'chamados',
                            'action' => 'ver-chamado',
                            'id_chamado' => $chamado->id_chamado
                        )); ?>">Ver</a>
                    </td>
                </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>
</div>