<div id="pages">
    <div id="gestor-chamdos-ver-chamado">
        <table>
            <tr>
                <th colspan="6">DADOS DO CHAMADO</th>
            </tr>
            <tr class="align_left">
                <th>Data Chamado: </th>
                <td><?php echo $this->dadosChamado->data_abertura; ?></td>
                <th>Tipo Chamado: </th>
                <td><?php echo $this->dadosChamado->descricao; ?></td>
                <th>Status: </th>
                <td><?php echo $this->dadosChamado->status; ?></td>
            </tr>
            <tr class="align_left">
                <th>Usuário: </th>
                <td><?php echo $this->dadosChamado->nome_completo; ?></td>
                <th>E-mail: </th>
                <td><?php echo $this->dadosChamado->email_usuario; ?></td>
                <th>CPF: </th>
                <td><?php echo $this->dadosChamado->cpf_usuario; ?></td>
            </tr>          
            <tr class="align_left">
                <th>Assunto:</th>
                <td colspan="5"><?php echo $this->dadosChamado->assunto; ?></td>
            </tr>
            <tr class="align_left">
                <th>Mensagem:</th>
                <td colspan="5"><?php echo $this->dadosChamado->mensagem; ?></td>
            </tr>
        </table>
    </div>
</div>