<div id="pages">
    <div id="chamdos-ver-chamdo">
        <table>
            <tr>
                <th colspan="6">DADOS DO CHAMADO</th>
            </tr>
            <tr class="align_left">
                <th>Data Chamado: </th>
                <td><?php echo $this->dadosChamado->data_abertura; ?></td>
                <th>Tipo Chamado: </th>
                <td><?php echo $this->dadosChamado->descricao; ?></td>
                <th>Status: </th>
                <td><?php echo $this->dadosChamado->status; ?></td>
            </tr>
            <tr class="align_left">
                <th>Usuário: </th>
                <td><?php echo $this->dadosChamado->nome_completo; ?></td>
                <th>E-mail: </th>
                <td><?php echo $this->dadosChamado->email_usuario; ?></td>
                <th>CPF: </th>
                <td><?php echo $this->dadosChamado->cpf_usuario; ?></td>
            </tr>          
            <tr class="align_left">
                <th>Assunto:</th>
                <td colspan="5"><?php echo $this->dadosChamado->assunto; ?></td>
            </tr>
            <tr class="align_left">
                <th>Mensagem:</th>
                <td colspan="5"><?php echo $this->dadosChamado->mensagem; ?></td>                
            </tr>
            <?php if ($this->dadosChamado->status == "ABC") : ?>
            <tr>
                <td colspan="6" class="align_right">
                    <a class="submit" href="<?php echo $this->url(array()); ?>">Fechar Chamado</a>
                </td>
            </tr>
            <?php endif; ?>
        </table>
        <?php if ($this->respostasChamado->count() > 0) : ?>
        <table>
            <tr>
                <th colspan="3">RESPOSTAS</th>
            </tr>
            <tr>
                <th width="200">Data Resposta</th>
                <th width="350">Usuário</th>
                <th>Resposta</th>
            </tr>      
            <?php foreach ($this->respostasChamado as $resposta) : ?>
            <tr>
                <td><?php echo View_Helper_Date::getDateTimeView($resposta->data_resposta); ?></td>
                <td><?php echo View_Helper_Application::isGestor($resposta->id_usuario) ? "Equipe NewFinances" : $resposta->nome_completo; ?></td>
                <td><?php echo $resposta->resposta; ?></td>
            </tr>
            <?php endforeach; ?>
        </table>
        <?php endif; ?>        
        <?php echo $this->formChamadosResponder; ?>
    </div>
</div>