<?php echo $this->headScript()->appendFile($this->baseUrl('views/js/site/slider.js')); ?>
<div id="jslidernews1" class="lof-slidecontent">
    <div class="preload"><div></div></div>
    <!-- MAIN CONTENT --> 
    <div class="main-slider-content" style="width:980px; height:340px;">
        <ul class="sliders-wrap-inner">
            <li>
                <img src="<?php echo $this->baseUrl('views/img/slider/banner_1.png'); ?>" title="Newsflash 2" >           
                <!--
                <div class="slider-description">
                    <div class="slider-meta"><a target="_parent'); ?>" title="Newsflash 1" href="#Category-1">/ Newsflash 1 /</a> <i> — Monday, February 15, 2010 12:42</i></div>
                    <h4>Content of Newsflash 1</h4>
                    <p>The one thing about a Web site, it always changes! Joomla! makes it easy to add Articles, content,...
                        <a class="readmore" href="#">Read more </a>
                    </p>
                </div>
                -->
            </li> 
            <li>
                <img src="<?php echo $this->baseUrl('views/img/slider/banner_2.png'); ?>" title="Newsflash 1" >           
                <!--
                <div class="slider-description">
                    <div class="slider-meta"><a target="_parent'); ?>" title="Newsflash 2" href="#Category-2">/ Newsflash 2 /</a> 	<i> — Monday, February 15, 2010 12:42</i></div>
                    <h4>Content of Newsflash 2</h4>
                    <p>Joomla! makes it easy to launch a Web site of any kind. Whether you want a brochure site or you are...
                        <a class="readmore" href="#">Read more </a>
                    </p>
                </div>
                -->
            </li> 
            <li>
                <img src="<?php echo $this->baseUrl('views/img/slider/banner_3.png'); ?>" title="Newsflash 3" >            
                <!--
                <div class="slider-description">
                    <div class="slider-meta"><a target="_parent'); ?>" title="Newsflash 3" href="#Category-3">/ Newsflash 3 /</a> 	<i> — Monday, February 15, 2010 12:42</i></div>
                    <h4>Content of Newsflash 3</h4>
                    <p>With a library of thousands of free Extensions, you can add what you need as your site grows. Don't...
                        <a class="readmore" href="#">Read more </a>
                    </p>
                </div>
                -->
            </li> 
            <li>
                <img src="<?php echo $this->baseUrl('views/img/slider/banner_4.png'); ?>" title="Newsflash 5" >            
                <!--
                <div class="slider-description">
                    <div class="slider-meta"><a target="_parent'); ?>" title="Newsflash 4" href="#Category-4">/ Newsflash 4 /</a>	<i> — Monday, February 15, 2010 12:42</i></div>
                    <h4>Content of Newsflash 4</h4>
                    <p>Joomla! 1.5 - 'Experience the Freedom'!. It has never been easier to create your own dynamic Web...
                        <a class="readmore" href="#">Read more </a>
                    </p>
                </div>
                -->
            </li> 
            <li>
                <img src="<?php echo $this->baseUrl('views/img/slider/banner_5.png'); ?>" title="Newsflash 5" >            
                <!--
                <div class="slider-description">
                    <div class="slider-meta"><a target="_parent'); ?>" title="Newsflash 5" href="#">/ Newsflash 5 /</a>	<i> — Monday, February 15, 2010 12:42</i></div>
                    <h4>Content of Newsflash 5</h4>
                    <p>Joomla! 1.5 - 'Experience the Freedom'!. It has never been easier to create your own dynamic Web...
                        <a class="readmore" href="#">Read more </a>
                    </p>
                </div>
                -->
            </li>  
        </ul>  	
    </div>
    <!-- END MAIN CONTENT --> 
    <!-- NAVIGATOR -->
    <!--
    <div class="navigator-content">
        <div class="button-next">Next</div>
        <div class="navigator-wrapper">
            <ul class="navigator-wrap-inner">
                <li><img src="<?php echo $this->baseUrl('views/img/slider/banner_1_mini.png'); ?>" /></li>
                <li><img src="<?php echo $this->baseUrl('views/img/slider/banner_2_mini.png'); ?>" /></li>
                <li><img src="<?php echo $this->baseUrl('views/img/slider/banner_3_mini.png'); ?>" /></li>
                <li><img src="<?php echo $this->baseUrl('views/img/slider/banner_4_mini.png'); ?>" /></li>    
                <li><img src="<?php echo $this->baseUrl('views/img/slider/banner_5_mini.png'); ?>" /></li>       		
            </ul>            
        </div>
        <div  class="button-previous">Previous</div>
    </div> 
    -->
    <!----------------- END OF NAVIGATOR --------------------->
    <!-- BUTTON PLAY-STOP -->
    <div class="button-control"><span></span></div>
    <!-- END OF BUTTON PLAY-STOP -->

</div>