<div id="pages">
    <div id="metas-editar">        
        <fieldset>
            <legend><?php echo $this->titulo; ?></legend>
            <?php echo $this->formMeta; ?>        
        </fieldset>        
        <table class="tabless-green">
            <tr>
                <td>Categoria</td>
                <td>Meta</td>
                <td colspan="2">Ações</td>
            </tr>
            <?php foreach ($this->metasUsuario as $meta) : ?>
            <tr>
                <td><?php echo $meta->descricao_categoria; ?></td>
                <td><?php echo View_Helper_Currency::getCurrency($meta->valor_meta); ?></td>
                <td>
                    <a href="<?php echo $this->url(array(
                        'action' => 'editar-meta',
                        'id_meta' => $meta->id_meta
                    )); ?>">
                        <img src="<?php echo $this->baseUrl('views/img/icon_edit.png'); ?>" title="Editar" />
                    </a>
                </td>
                <td>
                    <a href="<?php echo $this->url(array(
                        'action' => 'excluir-meta',
                        'id_meta' => $meta->id_meta
                    )); ?>">
                        <img src="<?php echo $this->baseUrl('views/img/icon_delete.png'); ?>" title="Editar" />
                    </a>
                </td>
            </tr>
            <?php endforeach; ?>
        </table>
        
    </div>
</div>