<?php echo $this->headLink()->appendStylesheet($this->baseUrl('views/css/meta/index.css')); ?>
<?php echo $this->headScript()->appendFile($this->baseUrl('views/js/meta/index.js')); ?>
<div id="pages">
    <div id="metas-index"> 
        <fieldset>
            <legend>Novo Orçamento</legend>
            <form method="post">
                
                <table>                    
                    <tr>
                        <td><?php echo $this->formMetas->id_categoria; ?> </td>
                    </tr>
                    <tr>
                        <td><?php echo $this->formMetas->valor_meta; ?> </td>
                    </tr>
                    <tr>
                        <td>
                            <?php echo $this->formMetas->repetir; ?> 
                            <span id="label-repetir-meta">Repete o lançamento desta meta para os outros meses.</span>
                        </td>
                    </tr>
                    <tr>
                        <td><?php echo $this->formMetas->submit; ?> </td>
                    </tr>
                    <tr>
                        <td>
                            <?php echo $this->formMetas->id_usuario; ?> 
                            <?php echo $this->formMetas->mes_meta; ?> 
                            <?php echo $this->formMetas->ano_meta; ?> 
                        </td>
                    </tr>
                </table>                
            </form>     
        </fieldset>        
        <div style="margin-top: 10px;">
            <table class="tabless-green">
                <tr>
                    <td>Categoria</td>
                    <td>Meta</td>
                    <td>Gastos</td>
                    <td>Porcentagem</td>
                    <td>Projeção</td>
                    <td colspan="2">Ações</td>
                </tr>
                <?php if ($this->metasUsuario->count() > 0) : ?>
                <?php foreach ($this->metasUsuario as $meta) : ?>
                
                <?php $total_gasto = View_Helper_Meta::getTotalGastosMetaMes($meta->id_categoria); ?>
                <?php $porcentagem = View_Helper_Meta::getPorcentagemTotalGastos($meta->valor_meta, $total_gasto) ?>
                <?php $projecao = View_Helper_Meta::getProjecaoMeta($porcentagem); ?>
                
                <tr>
                    <td><?php echo $meta->descricao_categoria; ?></td>
                    <td><?php echo View_Helper_Currency::getCurrency($meta->valor_meta); ?></td>
                    <td><?php echo $total_gasto; ?></td>
                    <td><?php echo $porcentagem; ?></td>
                    <td><?php echo $projecao; ?></td>
                    <td>
                        <a href="<?php echo $this->url(array(
                            'action' => 'editar-meta',
                            'id_meta' => $meta->id_meta
                        )); ?>">
                            <img src="<?php echo $this->baseUrl('views/img/icon_edit.png'); ?>" title="Editar" width="20" />
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array(
                            'action' => 'excluir-meta',
                            'id_meta' => $meta->id_meta
                        )); ?>">
                            <img src="<?php echo $this->baseUrl('views/img/icon_delete.png'); ?>" title="Excluir"  width="20" />
                        </a>
                    </td>
                </tr>
                <?php endforeach; ?>
                <tr>
                    <th>Total: </th>
                    <td><?php echo View_Helper_Currency::getCurrency($this->total_meta); ?></td>
                </tr>
                <?php else : ?>
                <tr>
                    <td>Nenhuma meta cadastrada</td>
                </tr>
                <?php endif; ?>
            </table>
        </div>
    </div>
</div>