<div style="float: left; width: 70%; margin: 10px 15%; border: 1px solid #696969; padding: 0 7px;">
    <div style="float: left; width: 100%; height: 250px;">
        <img style="padding: 15px; width: 250px;" src="<?php echo $this->baseUrl('views/img/logo_newfinances.png'); ?>" />
        <div style="float: left; width: 100%; padding: 7px;">
            <h2 style="text-align: center; margin: 10px 0;">{TÍTULO DA MENSAGEM}</h2 >
            <p>Olá {NOME USUÁRIO}</p>
            <p>{CORPO DO EMAIL}</p>
        </div>
    </div>
    <div style="position: relative; bottom: 0; left: 0;">
        <p style="text-align: center;">E-mail gerado automaticamente. Por favor não responda ao mesmo.</p>
        <p style="font-size: 16px; margin-top: 15px;">Atenciosamente,</p>
        <p style="font-weight: bold; font-size: 16px; margin-bottom: 7px;">Equipe NewFinances - contato@newfinances.com.br</p>        
    </div>
</div>