<?php echo $this->headLink()->appendStylesheet($this->baseUrl('views/css/cliente/politica/termo.css')); ?> 
<div id="pages">
    <div id="cliente-politica-termo">
        <h2>Termos e Condições de Uso do Site</h2>
        <ul>
            <li>
                <p class="bold">1. Aceitação dos Termos e Condições de Uso</p>
                <p class="align_justify">
                    O uso do sistema NewFinances Controle de Finanças oferecido 
                    pela StyleSheets Sistemas Web Ltda está condicionado à 
                    aceitação e ao cumprimento dos Termos e Condições de Uso 
                    descritos abaixo. 
                    <p>Para fazer uso do Sistema é preciso: <br /></p>
                    (i) ler atentamente os termos descritos abaixo;<br />
                    (ii) concordar expressamente com eles ao fazer uso do 
                        sistema, você (a partir de agora denominado Usuário) 
                        concorda que leu, entendeu e aceitou os termos, regras 
                        e condições aqui dispostos. Os Termos e Condições de 
                        Uso regulamentam a utilização do sistema, que pertencem 
                        à StyleSheets Sistemas WEb, devidamente inscrita no 
                        CNPJ/MF sob o nº XX.XXX.XXX.XXXX-XX.
                        
                    <p>
                        A StyleSheets se reserva o direito de modificar a 
                        qualquer momento a apresentação, configuração e 
                        disponibilização do sistema. O mesmo se aplica a estes 
                        Termos e Condições de Uso, estabelecidos como condição 
                        fundamental para a utilização do serviço.
                    </p>
                </p>
            </li>
            <li>
               <p class="bold">2. Cadastro</p>
               <p class="align_justify"> 
                   <p>
                    O Usuário declara e se responsabiliza pela veracidade de 
                    todos os dados por ele fornecidos ao sistema no momento de 
                    seu Cadastro e em qualquer atualização posterior, ficando 
                    responsável, portanto, pela sua exatidão e autenticidade.
                   </p>
                   <p>
                    É dever do Usuário manter seus dados atualizados para a 
                    devida utilização do sistema.
                   </p>
                   <p>
                    Somente será permitido um único Cadastro por Usuário, 
                    sendo necessário para sua efetivação o preenchimento de 
                    todos os campos exigidos no respectivo formulário.
                    No momento do Cadastro, o Usuário deverá informar um e-mail 
                    válido e senha, pessoal e intransferível, por meio dos quais 
                    ele terá acesso ao sistema, comprometendo-se a não 
                    informá-los a terceiros, responsabilizando-se exclusiva e 
                    pessoalmente pelo seu uso.
                   </p>
                   <p>
                    A StyleSheets se reserva o direito de, a qualquer tempo, 
                    ao seu livre e exclusivo critério e sem aviso prévio:<br />
                    (i) conferir os dados informados pelo Usuário no Cadastro do
                    sistema, podendo solicitar dados e/ou documentos adicionais.<br />
                    (ii) cancelar ou excluir os Cadastros de Usuários que 
                    estejam inativos há mais de 90 (noventa) dias. Para tanto, 
                    a StyleSheets encaminhará um e-mail ao Usuário, para o 
                    endereço que este informou em seu Cadastro e, caso não haja 
                    nenhuma resposta ou atividade no Sistema dentro de, até, 30 
                    (trinta) dias contados do envio de tal e-mail, a StyleSheets
                    procederá ao cancelamento do Cadastro e exclusão do Usuário 
                    do banco de dados.
                   </p>
                   <p>
                    O Usuário se compromete a comunicar imediatamente à 
                    StyleSheets a eventual perda ou roubo de sua senha de acesso, 
                    assim como qualquer risco de acesso a ela por terceiros.
                   </p>
                   <p>
                    É recomendável ao Usuário trocar de senha periodicamente, 
                    o que pode ser feito acessando-se a página no Sistema.
                   </p>
               </p>
            </li>            
            <li>
               <p class="bold">3. Utilização do Sistema</p>
               <p class="align_justify"> 
                   O Usuário reconhece que é responsável por quaisquer informações falsas que possam ser prestadas para a utilização do Sistema. O Usuário isenta a StyleSheets de qualquer responsabilidade quanto à veracidade dos dados pessoais fornecidos por ele quando do uso do Sistema.
O usuário reconhece, ainda, que estes Termos e Condições de Uso do Sistema oferecida pela StyleSheets devem ser observados e fielmente cumpridos, sob pena de cancelamento de bloqueio de utilização do Sistema e demais medidas cabíveis, caso os mencionados Termos forem violados ou descumpridos.

               </p>
            </li>            
            <li>
               <p class="bold">4. Registro e dados pessoais</p>
               <p class="align_justify"> 
                   É dever do Usuário manter atualizados os dados pessoais fornecidos quando da utilização do Sistema.
A Empresa pode cancelar qualquer registro do Usuário, a qualquer momento e sem prévio aviso, assim que tiver conhecimento, e a seu exclusivo critério, se o Usuário descumprir, intencionalmente ou não, estes Termos e Condições de Uso, ou violar leis e regulamentos federais, estaduais e/ou municipais, ou violar os princípios legais, a moral e os bons costumes.
Os Usuários que tiverem seus registros cancelados não poderão mais utilizar o Sistema.

               </p>
            </li>            
            <li>
               <p class="bold">5. Regras de conduta do Usuário</p>
               <p class="align_justify"> 
                   O Usuário se compromete a não utilizar o Sistema para a publicação, criação, armazenamento e/ou divulgação de:
 a) Conteúdo abusivo, como textos, fotos e/ou vídeos que tenham caráter difamatório, discriminatório, obsceno, ofensivo, ameaçador, abusivo, vexatório, prejudicial, que contenha expressões de ódio contra pessoas ou grupos, ou que contenha pornografia infantil, pornografia explícita ou violenta, conteúdo que possa ser danoso a menores, que contenha insultos ou ameaças religiosas ou raciais, ou que incentive danos morais (incluindo os corporais) e patrimoniais, ou que possa violar qualquer direito de terceiro, notadamente os direitos humanos.
 b) Banners publicitários e/ou qualquer tipo de comércio eletrônico que seja considerado ilícito, assim entendidos os que sejam contrários à legislação ou ofendam direitos de terceiros.
 c) Qualquer tipo de material (textos, fotos e/ou vídeos) protegido por direitos autorais, copyright ou que, por qualquer razão, violem direitos de terceiros.
 d) Informações difamatórias e caluniosas ou que sejam contrárias à honra, à intimidade pessoal e familiar ou à imagem das pessoas (inclusive de pessoa jurídicas, entidades e organizações e ela equiparadas).
 e) Material que incite à violência e à criminalidade, bem como à pirataria de produtos.
 f) Conteúdo que provoque, por suas características (como extensões e formatos de arquivos) danos ao sistema da StyleSheets.
O Usuário concorda que, ao usar o Sistema, não irá:
 violar qualquer um destes Termos e Condições de Uso;
 praticar falsidade, assim entendidas a falsidade de informações (i.e: divulgação proposital e voluntária de informações que o Usuário saiba ser falsa ou que sejam notoriamente falsas) e a falsidade ideológica;
publicar ou transmitir qualquer conteúdo abusivo ou ofensivo nos comentários;
replicar ou armazenar conteúdo abusivo nos servidores da StyleSheets;
fazer qualquer coisa ou praticar qualquer ato contrário à boa-fé e aos usos e costumes das comunidades virtuais e que possam ofender qualquer direito de terceiros. Por violação aos usos e costumes de comunidades virtuais também deve ser entendido o uso excessivo de texto em letras maiúsculas, uso de críticas ofensivas (conhecidas como “flamming”), a inclusão desnecessária e imprudente de comunicações anteriores em qualquer publicação ou transmissão, bem como qualquer outro ato que esteja em desacordo com a etiqueta da Internet comumente aceita.
cometer fraude;
violar ou infringir direitos de propriedade intelectual, direitos fiduciários ou contratuais, direitos de privacidade ou publicidade de outros;
propagar, distribuir ou transmitir códigos destrutivos, quer tenham ou não causado danos reais;
reunir dados pessoais ou comerciais, incluindo (mas não se limitando a) endereços de e-mail e/ou nomes de qualquer recurso da Internet, seja gerenciado por nós ou por terceiros, para fins comerciais, políticos, de benemerência ou outros, sem o consentimento dos proprietários desses dados;
reproduzir, replicar, copiar, alterar, modificar, criar obras derivativas a partir de, vender ou revender qualquer um dos serviços da StyleSheets ou qualquer parte deles, incluindo websistemas e páginas web, ou as informações ou dados contidos nos serviços da StyleSheets;
usar robôs, “spiders” ou qualquer outro dispositivo, automático ou manual, para monitorar ou copiar qualquer conteúdo do serviço da StyleSheets;
transmitir conteúdo que não pertence ao Usuário ou que ele não tenha direito de publicar ou distribuir, seja sob lei ou contrato;
acessar o Sistema sem autorização, por meio de práticas de “hacking”, “password mining” ou qualquer outro meio fraudulento ou que represente violação a direito de terceiros;
realizar ou incentivar atividades ilegais, incluindo (mas não se limitando a) promover ou facilitar o acesso, uso ou venda de substâncias ou dispositivos perigosos;
deixar de cumprir com quaisquer leis, normas, regras, princípios e regulamentações aplicáveis;
ajudar qualquer terceiro a realizar qualquer uma das ações vedadas por estes Termos e Condições de Uso.
               </p>
            </li>            
            <li>
               <p class="bold">6. Denúncia de abusos e violação</p>
               <p class="align_justify"> 
                   O Usuário se compromete a denunciar quaisquer abusos ou violação destes Termos e Condições de Uso ou de quaisquer direitos de terceiros que observar e/ou for vítima quando da utilização do Sistema. O Usuário deve utilizar o canal disponibilizado no Sistema para comunicação com a StyleSheets.
Todo conteúdo que o Usuário publica utilizando qualquer fórum de discussão é uma informação que, por sua natureza e característica, é pública, aberta e não confidencial. Ao revelar dados pessoais, tais como seu nome e endereço de e-mail nos comentários, o Usuário aceita e compreende que essa informação pode ser coletada e usada por outras pessoas para se comunicarem com ele, sem que seja imputável qualquer responsabilidade à StyleSheets. Desta forma, a StyleSheets recomenda que o Usuário seja, portanto, cuidadoso ao decidir compartilhar qualquer dado pessoal em qualquer websistema.

               </p>
            </li>            
            <li>
               <p class="bold">7. Responsabilidades</p>
               <p class="align_justify"> 
                   A StyleSheets não se responsabiliza por quaisquer danos sofridos pelo Usuário ou terceiros que, de qualquer modo, tenha origem ou dependência relacionada ao Sistema.
A StyleSheets se exime de quaisquer responsabilidades sobre prejuízos resultantes de qualquer interrupção ou erro no Sistema virtuais da StyleSheets, incluindo a impossibilidade de acessar o Sistema e/ou os websistemas relacionados a ele.
A StyleSheets não é proprietária dos produtos oferecidos pelos Comerciantes [ou Anunciantes], não detém a posse deles, não realiza as ofertas de venda, tampouco, intervém na entrega dos produtos, cuja negociação se inicie no sistema.
O Usuário reconhece que não há nenhum envolvimento ou intervenção da StyleSheets nos negócios celebrados com os Comerciantes no sistema Info. Em nenhum caso StyleSheets será responsável por qualquer dano ou prejuízo sofrido pelo Usuário em decorrência das negociações realizadas por meio do sistema Info, em função da conduta dos Comerciantes, inclusive, mas não se limitando, fraudes ou estelionato on line.
A StyleSheets não tem a obrigação de controlar, e efetivamente não controla, a oferta e comercialização de Produtos nas Lojas Virtuais de terceiros, as condições de venda dos Produtos estabelecidas pelos Comerciantes, e o cumprimento, pelo Comerciante, das obrigações decorrentes da oferta e comercialização dos Produtos.
A StyleSheets também não se responsabiliza pela transação efetuada entre Usuário e Comerciante, pelo efetivo cumprimento das obrigações assumidas pelos Comerciantes, nem pela existência, quantidade, qualidade, estado, licitude, integridade ou legitimidade dos produtos oferecidos e/ou vendidos pelos Comerciantes no sistema Info. A StyleSheets não outorga garantia por vícios ocultos ou aparentes nos produtos e/ou nas negociações entre os Usuários e Comerciantes.
O Usuário reconhece e aceita que, ao realizar negociações com os Comerciantes, o faz por sua conta e risco, isentando a StyleSheets de qualquer responsabilidade

               </p>
            </li>            
            <li>
               <p class="bold">8. Privacidade de dados</p>
               <p class="align_justify"> 
                   A StyleSheets não se responsabiliza por quaisquer danos que o Usuário possa sofrer, que tenham origem na divulgação dos dados pessoais do Usuário ou de terceiros em materiais publicados em qualquer websistema.
A StyleSheets preserva a privacidade dos dados dos Usuários, e se compromete a revelar os dados pessoais do Usuário apenas devido a um dos seguintes motivos:
•	• por lei;
•	• por meio de uma ordem ou intimação de um órgão, autoridade ou tribunal com poderes para tanto e de jurisdição competente;
•	• para garantir a segurança dos sistemas, resguardar direitos e prevenir responsabilidades da StyleSheets.

               </p>
            </li>            
            <li>
               <p class="bold">9. Legislação aplicável</p>
               <p class="align_justify"> 
                   Estes Termos e Condições de Uso são governados e interpretados segundo as leis da República Federativa do Brasil e todas as disputas, ações e outros assuntos relacionados serão determinados de acordo com essa legislação.
               </p>
            </li>            
        </ul>
    </div>
</div>