<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <?php header("Content-Type: text/html; charset=UTF-8",true); ?>
        <?php echo $this->headTitle("NewFinances"); ?> 
        <!-- css -->
        <?php echo $this->headLink()->appendStylesheet($this->baseUrl('views/css/site.css')); ?>
        <?php echo $this->headLink()->appendStylesheet($this->baseUrl('views/css/default.css')); ?>
        <?php echo $this->headLink()->appendStylesheet($this->baseUrl('views/css/menu-site.css')); ?>         
        <?php echo $this->headLink()->appendStylesheet($this->baseUrl('views/css/jquery-ui-1.10.3.css')); ?> 
        
        <!-- arquivos js -->
        <?php echo $this->headScript()->appendFile($this->baseUrl('views/js/jquery-2.0.3.js')); ?>
        <?php echo $this->headScript()->appendFile($this->baseUrl('views/js/jquery-ui-1.10.3.js')); ?>    
        <?php echo $this->headScript()->appendFile($this->baseUrl('views/js/jquery.ui.datepicker-pt-BR.js')); ?>    
        <?php echo $this->headScript()->appendFile($this->baseUrl('views/js/jquery.maskedinput.js')); ?>
        <?php echo $this->headScript()->appendFile($this->baseUrl('views/js/jquery.maskMoney.js')); ?>          
        <?php echo $this->headScript()->appendFile($this->baseUrl('views/js/application.js')); ?>
        <?php echo $this->headScript()->appendFile($this->baseUrl('views/js/facebook.js')); ?>
        <?php //echo $this->headScript()->appendFile($this->baseUrl('views/js/jsapi.js')); ?>  
        
    </head>
    <body>        
        <div id="content-all">   
            <div id="social-area">
                <div style="float: left; margin: 10px 0; ">   
                    <a href="<?php echo $this->url(array(
                        'module' => 'site',
                        'controller' => 'index',
                        'action' => 'index'
                    )); ?>">
                        <img src="<?php echo $this->baseUrl('views/img/logo_newfinances.png'); ?>" width="280" />                    
                    </a>
                </div>
                <div class="redes-sociais">
                    <a href="https://www.facebook.com/sisnewfinances" target="_blank" title="Acesse nossa página no Facebook">
                        <img src="<?php echo $this->baseUrl('views/img/icon_face_social.png'); ?>" />
                    </a>
                    <img src="<?php echo $this->baseUrl('views/img/icon_twitter_social.png'); ?>" />
                    <img src="<?php echo $this->baseUrl('views/img/icon_google_plus_social.png'); ?>" />
                </div>
                <div style="position: absolute; top: 40px; left: 45%;">
                    <span style="font-size: 20px; font-weight: bold;">
                        <?php echo ($_SERVER['SERVER_NAME'] == "localhost") ? "Base de Testes" : ""; ?>
                    </span>
                </div>
            </div>
            <div id="menus">
                <ul id="saturday">
                    <li>
                        <a href="<?php echo $this->url(array(
                            'module' => 'site',
                            'controller' => 'index',
                            'action' => 'index'
                        ), null, true); ?>" class="current"><span>Início</span></a>
                    </li>                    
                    <li>
                        <a href="<?php echo $this->url(array(
                            'module' => 'site',
                            'controller' => 'planos',
                            'action' => 'index'
                        ), null, true); ?>"><span>Nossos Planos</span></a>
                    </li>
                    <?php if (!Zend_Auth::getInstance()->hasIdentity()) : ?>
                    <li>
                        <a href="<?php echo $this->url(array(
                            'module' => 'cliente',
                            'controller' => 'usuarios',
                            'action' => 'novo-usuario'
                        ), null, true); ?>"><span>Cadastre-se</span></a>
                    </li>
                    <?php endif; ?>
                    <?php if (Zend_Auth::getInstance()->hasIdentity()) : ?>
                    <li style="float: right; ">
                        <a href="<?php echo $this->url(array(
                            'module' => 'cliente',
                            'controller' => 'index',
                            'action' => 'index'
                        ), null, true); ?>"><span>Voltar para minha conta</span></a>
                    </li>
                    <?php else : ?>
                    <li style="float: right; ">
                        <a href="<?php echo $this->url(array(
                            'module' => 'cliente',
                            'controller' => 'usuarios',
                            'action' => 'login'
                        ), null, true); ?>"><span>Acesse sua conta</span></a>
                    </li>          
                    <?php endif; ?>
                </ul>
            </div>
            <div id="content">
                <?php echo $this->layout()->content; ?>
            </div>
            <div id="paseguro">
                <span><h4><b>Formas de Pagamentos:<b></h4></span>
                <p>
                    <img src="<?php echo $this->baseUrl('views/img/icon_cards_payment.png'); ?>" />
                </p>
            </div>            
            <div id="footer">
                <p>
                    <a href="<?php echo $this->url(array(
                        'module' => 'cliente',
                        'controller' => 'politica',
                        'action' => 'termo'
                    )); ?>">Termo de Uso</a>
                    | 
                    <a href="<?php echo $this->url(array(
                        'module' => 'cliente',
                        'controller' => 'politica',
                        'action' => 'index'
                    )); ?>">Política de Privacidade</a>
                </p>
                <p>Contato: contato@newfinances.w.pw</p>
                <span>Todos os direitos reservados.</span>
            </div>
        </div>
    </body>
</html>